myrobogals/core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, routers
from api_1_0 import views

############# Django REST Framework ###############
api_router = routers.DefaultRouter()
api_router.register(r'users', views.UserViewSet)
api_router.register(r'groups', views.GroupViewSet)
####################################################

# Auto generate/collate Django admin panels
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myrobogals.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # Django REST Framework
    url(r'^api/1.0/', include(api_router.urls)),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
)

myrobogals/myrg_core/urls.py
from __future__ import unicode_literals
from future.builtins import *
import six

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import Group
from myrg_users.models import RobogalsUser

from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from myrg_core.views import Time
from myrg_users.views import ListUsers, DeleteUsers, EditUsers, CreateUsers, ResetUserPasswords, ResetUserPasswordsComplete, WhoAmI, ListMyRoles, KillSessions
from myrg_groups.views import ListGroups, DeleteGroups, EditGroups, CreateGroups, ListRoles, EditRoles, CreateRoles, ListRoleClasses, DeleteRoleClasses, EditRoleClasses, CreateRoleClasses
from myrg_messages.views import SendMessage, ListEmailDefinition, ListEmailMessage
from myrg_repo.views import ListRepoFiles, DeleteRepoFiles, ListRepoContainers, DeleteRepoContainers, EditRepoContainers, CreateRepoContainers
from myrg_permissions.views import ListPermission, DeletePermissionLists, EditPermissionLists, CreatePermissionLists

# Auto generate/collate Django admin panels
admin.autodiscover()
admin.site.unregister(Group)

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    # Django REST Framework
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),

    # OAuth Django Toolkit
    url(r'^api/o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
)

# API 1.0
api_urlpatterns = patterns('',
    url(r'^api/1.0/utils/time$', Time.as_view()),
    url(r'^api/1.0/utils/pwdreset/initiate$', ResetUserPasswords.as_view()),
    url(r'^api/1.0/utils/pwdreset/complete', ResetUserPasswordsComplete.as_view()),

    url(r'^api/1.0/self/whoami$', WhoAmI.as_view()),
    url(r'^api/1.0/self/roles$', ListMyRoles.as_view()),
    url(r'^api/1.0/self/killsessions$', KillSessions.as_view()),

    url(r'^api/1.0/users/list$', ListUsers.as_view()),
    url(r'^api/1.0/users/delete$', DeleteUsers.as_view()),
    url(r'^api/1.0/users/edit$', EditUsers.as_view()),
    url(r'^api/1.0/users/create$', CreateUsers.as_view()),

    url(r'^api/1.0/groups/list$', ListGroups.as_view()),
    url(r'^api/1.0/groups/delete$', DeleteGroups.as_view()),
    url(r'^api/1.0/groups/edit$', EditGroups.as_view()),
    url(r'^api/1.0/groups/create$', CreateGroups.as_view()),

    url(r'^api/1.0/roles/list$', ListRoles.as_view()),
    url(r'^api/1.0/roles/edit$', EditRoles.as_view()),
    url(r'^api/1.0/roles/create$', CreateRoles.as_view()),

    url(r'^api/1.0/roleclasses/list$', ListRoleClasses.as_view()),
    url(r'^api/1.0/roleclasses/delete$', DeleteRoleClasses.as_view()),
    url(r'^api/1.0/roleclasses/edit$', EditRoleClasses.as_view()),
    url(r'^api/1.0/roleclasses/create$', CreateRoleClasses.as_view()),
    
    url(r'^api/1.0/emailmessage/list$', ListEmailMessage.as_view()),
    url(r'^api/1.0/emaildefinitions/list$', ListEmailDefinition.as_view()),
    url(r'^api/1.0/repofiles/list$', ListRepoFiles.as_view()),
    url(r'^api/1.0/repofiles/delete$', DeleteRepoFiles.as_view()),
    url(r'^api/1.0/repofiles/create', 'myrg_repo.views.upload', name='upload'),

    url(r'^api/1.0/repocontainers/list$', ListRepoContainers.as_view()),
    url(r'^api/1.0/repocontainers/delete$', DeleteRepoContainers.as_view()),
    url(r'^api/1.0/repocontainers/edit$', EditRepoContainers.as_view()),
    url(r'^api/1.0/repocontainers/create$', CreateRepoContainers.as_view()),
    
    url(r'^api/1.0/permissions/list$', ListPermission.as_view()),
    url(r'^api/1.0/permissions/delete$', DeletePermissionLists.as_view()),
    url(r'^api/1.0/permissions/edit$', EditPermissionLists.as_view()),
    url(r'^api/1.0/permissions/create$', CreatePermissionLists.as_view()),

    url(r'^api/1.0/emailmessage/list$', ListEmailMessage.as_view()),
    url(r'^api/1.0/emaildefinitions/list$', ListEmailDefinition.as_view()),
    url(r'^api/1.0/messages/send$', SendMessage.as_view()),
)

api_urlpatterns = format_suffix_patterns(api_urlpatterns, allowed=['json'])

urlpatterns += api_urlpatterns

urlpatterns += patterns('',
    url(r'^app/login$', 'myrg_webapp.views.login', name='login'),
    url(r'^app/logout$', 'myrg_webapp.views.logout', name='logout'),
    url(r'^app/set_role_id$', 'myrg_webapp.views.set_role_id'),
    url(r'^app/resource/(?P<resource_id>.+?)$', 'myrg_webapp.views.get_resource'),
    
    url(r'^$', 'myrg_webapp.views.webapp', name='home'),
    url(r'^app/url/csv', 'myrg_reports.csv.convert_csv_direct', name='csv_direct'),
    url(r'^app/csv', 'myrg_reports.csv.convert_csv', name='csv'),
    #url(r'^app/report', 'myrg_reports.views.my_report', name='report')
    #url(r'^/(?P<app_label>[\d\w]+)/(?P<model_name>[\d\w]+)/csv/', 'myrg_repo.views.convert_csv')
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myrobogals/rgreport/urls.py
from django.conf.urls import url
from myrobogals.rgreport import views as report

urlpatterns = [
    url(r'^$', report.report_standard, name='standard'),
    url(r'^global/$', report.report_global, name='global'),
    url(r'^global/old/$', report.report_global_old, name='global_old'),  # TESTING PURPOSES ONLY
    url(r'^global/breakdown/(?P<chaptershorten>.+)/$', report.report_global_breakdown, name='global_breakdown'),
    url(r'^progress/$', report.progresschapter, name='progress'),
]

myrobogals/urls.py
from django.conf.urls import url, include, i18n
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve as static_serve_view
from tinymce import urls as tinymce_urls

from myrobogals import settings
from myrobogals.rgchapter import views as rgchapter_views
from myrobogals.rgconf import views as rgconf_views
from myrobogals.rgmain import views as rgmain_views
from myrobogals.rgmessages import views as rgmessages_views
from myrobogals.rgprofile.views import profile_chapter, profile_user, profile_login
from myrobogals.rgweb import views as rgweb_views

urlpatterns = [
	# Home
	url(r'^$', rgmain_views.home),

	# User functions
	url(r'^login/$', profile_login.show_login),
	url(r'^logout/$', auth_views.logout, {'next_page': '/'}),
	url(r'^chpass/$', auth_views.password_change, {'template_name': 'password_change_form.html', 'post_change_redirect': '/profile'}),
	url(r'^forgotpass/done/$', auth_views.password_reset_done, {'template_name': 'password_reset_done.html'}, name='password_reset_done'),
	url(r'^forgotpass/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'password_reset_confirm.html'}),
	url(r'^forgotpass/complete/$', auth_views.password_reset_complete, {'template_name': 'password_reset_complete.html'}, name='password_reset_complete'),
	url(r'^forgotpass/$', auth_views.password_reset, {'template_name': 'password_reset_form.html', 'email_template_name': 'password_reset_email.html'}),
	#url(r'^unsubscribe/(?P<uidb36>.+)/(?P<token>.+)/(?P<step>\d)/$', auth_views.unsubscribe),
	url(r'^join/$', rgchapter_views.joinlist),
	url(r'^join/(?P<chapterurl>.+)/$', profile_user.joinchapter),
	url(r'^welcome/(?P<chapterurl>.+)/$', rgmain_views.welcome),
	url(r'^code/$', profile_login.codeofconduct),
	url(r'^code/help/$', profile_user.conduct_help),

	# Profile menu
	url(r'^profile/$', profile_user.redirtoself),
	url(r'^profile/contactdirectory/$', profile_chapter.contactdirectory),
	url(r'^profile/edit/$', profile_user.redirtoeditself),
	url(r'^profile/mobverify/$', profile_user.mobverify),
	#url(r'^profile/(?P<username>.+)/edit/profileimage/$', 'profileimages.views.upload_profile_image'),
	url(r'^profile/(?P<username>.+)/edit/$', profile_user.edituser),
	url(r'^profile/(?P<username>.+)/genpw/$', profile_user.genpw),
	url(r'^profile/(?P<username>.+)/$', profile_user.detail),
	
	# Chapters menu
	url(r'^chapters/$', rgchapter_views.list),
	url(r'^chapters/awards/$', rgchapter_views.awards),
	url(r'^chapters/awards/(?P<award_id>\d+)/$', rgchapter_views.awardsdesc),
	url(r'^chapters/my/$', rgchapter_views.redirtomy),
	url(r'^chapters/localtimes/$', rgchapter_views.localtimes),
	url(r'^chapters/(?P<chapterurl>.+)/lists/(?P<list_id>\d+)/edit/$', profile_chapter.edituserlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/(?P<list_id>\d+)/$', profile_chapter.viewlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/add/$', profile_chapter.adduserlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/$', profile_chapter.listuserlists),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/help/unis/$', profile_chapter.unilist),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/help/$', profile_chapter.importusershelp),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/$', profile_chapter.importusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/export/$', profile_chapter.exportusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/add/$', profile_chapter.adduser),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/$', profile_chapter.editusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/execs/remove/(?P<username>.+)/$', profile_chapter.remove_exec),
	url(r'^chapters/(?P<chapterurl>.+)/edit/execs/$', profile_chapter.editexecs),
	url(r'^chapters/(?P<chapterurl>.+)/edit/status/$', profile_chapter.editstatus),
	url(r'^chapters/(?P<chapterurl>.+)/edit/$', rgchapter_views.editchapter),
	url(r'^chapters/(?P<chapterurl>.+)/websitedetails/$', rgweb_views.websitedetails),
	url(r'^chapters/(?P<chapterurl>.+)/join/$', profile_user.joinchapter),
	url(r'^chapters/(?P<chapterurl>.+)/$', rgchapter_views.detail),

	# Conferences submenu
	url(r'^conferences/$', rgconf_views.home),
	url(r'^conferences/(?P<conf_id>\d+)/$', rgconf_views.rsvplist),
	url(r'^conferences/(?P<conf_id>\d+)/nametags\.csv$', rgconf_views.nametagscsv),
	url(r'^conferences/(?P<conf_id>\d+)/email/$', rgconf_views.rsvpemail),
	url(r'^conferences/(?P<conf_id>\d+)/(?P<username>.+)/rsvp/$', rgconf_views.editrsvp),
	url(r'^conferences/(?P<conf_id>\d+)/(?P<username>.+)/invoice/$', rgconf_views.showinvoice),

	# Forums
	# url(r'^forums/', include('myrobogals.rgforums.urls')),

	# Workshops menu
	url(r'^teaching/', include('myrobogals.rgteaching.urls', namespace='teaching')),

	# Reporting metrics
	url(r'^reports/', include('myrobogals.rgreport.urls', namespace='reports')),

	# Email & SMS menu
	url(r'^messages/img/(?P<msgid>\d+)/(?P<filename>.+)$', rgmessages_views.serveimg),
	url(r'^messages/(?P<msgid>\d+)/(?P<issue>.+)/$', rgmessages_views.servenewsletter),
	url(r'^messages/sms/write/$', rgmessages_views.writesms),
	url(r'^messages/sms/done/$', rgmessages_views.smsdone),
	url(r'^messages/sms/overlimit/$', rgmessages_views.smsoverlimit),
	url(r'^messages/email/write/$', rgmessages_views.writeemail),
	url(r'^messages/setmaxuploadfilesize/$', rgmessages_views.setmaxuploadfilesize),
	url(r'^messages/email/done/$', rgmessages_views.emaildone),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/$', rgmessages_views.newslettercp),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/import/$', rgmessages_views.importsubscribers),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/import/help/$', rgmessages_views.importsubscribershelp),
	url(r'^messages/emailrecipients/(?P<email_id>\d+)/$', rgmessages_views.emailrecipients),
	url(r'^messages/smsrecipients/(?P<sms_id>\d+)/$', rgmessages_views.smsrecipients),
	url(r'^messages/showemail/(?P<email_id>\d+)/$', rgmessages_views.showemail),
	url(r'^messages/downloademailfile/(?P<email_id>\d+)/(?P<file_name>.+)/$', rgmessages_views.downloademailfile),
	url(r'^messages/history/$', rgmessages_views.msghistory),
	url(r'^messages/previewemail/$', rgmessages_views.previewemail),
	
	# Changelogs
	url(r'^changelogs/$', rgmain_views.changelogs),

	# Wiki
	url(r'^wiki/$', rgmain_views.wiki),

	# Static pages
	url(r'^credits/$', rgmain_views.credits),
	url(r'^support/$', rgmain_views.support),

	# Careers newsletter API
	url(r'^api/newslettercareers/$', rgmessages_views.careersapi),
	# Amplifier newsletter API
	url(r'^api/newsletter/$', rgmessages_views.api),
	# SMSGlobal delivery receipts API
	url(r'^api/dlr/$', rgmessages_views.dlrapi),
	# Google Maps KML API
	url(r'^api/chapter-map.kml', rgchapter_views.chaptermap),
	# Delete user API
	url(r'^delete/user/(?P<userpk>\d+)/$', profile_chapter.deleteuser),

	# i18n helpers
	url(r'^i18n/', include(i18n)),
	# TinyMCE helpers
	url(r'^tinymce/', include(tinymce_urls)),
	
	# Admin site
	url(r'^topsecretarea/', include(admin.site.urls)),
]

# If running the local development server - this will serve the media files through it too
if settings.DEBUG:
	urlpatterns.append(url(r'^rgmedia/(?P<path>.*)$', static_serve_view, {'document_root': settings.MEDIA_ROOT}))

# Custom view for 500 Internal Server Error
handler500 = 'myrobogals.rgmain.views.servererror'

templates/base-v2.html
{% load static %}
{% load nav %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>myRobogals - {% block title %}{% endblock %}</title>

  <!-- 3rd party css-->
{#  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">#}
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/css/bootstrap-timepicker.min.css"/>

  <!-- Bootstrap core CSS -->
  <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
  <link href="{% static "bootstrap-v4/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "myrobogals/css/base_new.css" %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static "bootstrap/css/sticky-footer-navbar.css" %} " rel="stylesheet">
  {#  <link href="{% static "bootstrap-datepicker/css/bootstrap-datepicker3.standalone.min.css" %}"#}

  {% block header %} {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{{ MEDIA_URL }}images/logowhite.png" height="25">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% active_nav request 'chapters' %}">
          <a class="nav-link thick-font" href="{% url 'chapters:home' request.user.chapter.myrobogals_url %}">CHAPTER</a>
        </li>
        <li class="nav-item {% active_nav request 'teaching' %}">
          <a class="nav-link thick-font" href="{% url 'teaching:home' %}">EVENTS</a>
        </li>
        <li class="nav-item {% active_nav request 'reports' %}">
          <a class="nav-link thick-font" href="{% url 'reports:standard' %}">REPORTS</a>
        </li>
        <li class="nav-item {% active_nav request 'forums' %}">
          <a class="nav-link thick-font" href="#">FORUMS</a>
        </li>
        <li class="nav-item {% active_nav request 'wiki' %}">
          <a class="nav-link thick-font" href="#">WIKI</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-lg" aria-hidden="true"></i><span
              class="caret"></span></a></a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url "profile" %}">View Profile</a>
            <a class="dropdown-item" href="#">Edit Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Contact Directory</a>
            <a class="dropdown-item" href="#">Support & FAQ</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url "logout" %}">Logout</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Begin page content -->
<div class="page-title">
  <div class="container">
    <h1>{% block pagetitle %} {% endblock %}</h1>
  </div>
</div>

<div class="container main-body">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item active">Report Summary</li>
  </ol>

  {% for message in messages %} {% autoescape off %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      <div class="alert alert-danger"><strong>Oops,</strong> {{ message }} </div>
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      <div class="alert alert-info"><strong>FYI,</strong> {{ message }} </div>
    {% else %}
      <div class="alert alert-success"><strong>Success!</strong> {{ message }}</div>
    {% endif %} {% endautoescape %}
  {% endfor %}

  {% block content %} {% endblock %}
</div>

<footer class="footer">
  <div class="container text-muted">
    <select>
      <option value="english">English</option>
      <option value="japanese">Japanese</option>
    </select>
    &copy; Robogals 2010-2017
    <a href="/credits/">Credits</a> | <a href="/support/">Support</a> | <a href="http://robogals.org">robogals.org</a>
  </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://unpkg.com/popper.js"></script>
<script src="{% static "bootstrap-v4/js/bootstrap.min.js" %}"></script>
<script src="{% static "bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/js/bootstrap-timepicker.min.js" integrity="sha256-bmXHkMKAxMZgr2EehOetiN/paT9LXp0KKAKnLpYlHwE="
        crossorigin="anonymous"></script>
<script src="{% static "bootstrap-typeahead/js/bootstrap3-typeahead.min.js" %}"></script>
{% block script %} {% endblock %}
</body>
</html>

templates/password_reset_complete_v2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>myRobogals</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ MEDIA_URL }}resources/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}resources/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}templates/system/css/landing.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>

<body style="background: url('{{ MEDIA_URL }}images/low-poly-wallpaper-22.png');">
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <div class="heading">
                    <h1 class="cover-heading">Password reset</h1>
                    <h4 class="cover-quote" id="quote"> Password Reset</h4>
                    <p>
                        Your password has been changed. Click below to login in with your new password.
                    </p>
                </div>

                <a href="/login">
                    <input type="submit" name="Submit" class="btn btn-md btn-default" value="Go To Login"/>
                </a>


                <div class="row">
                    <div class="col-md-4" style=""><a href="/">Home</a></div>
                    <div class="col-md-1">-</div>
                    <div class="col-md-2"><a href="/join/">Sign up!</a></div>
                    <div class="col-md-1">-</div>
                    <div class="col-md-4"><a href="/support/">Contact Us &amp; FAQ</a></div>
                </div>
            </div>

            <!--Footer -->
            <div class="mastfoot">
                <div class="media-icons">
                    <a href="https://www.facebook.com/robogals/"><i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a>
                    <a href="https://twitter.com/robogals"><i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i></a>
                    <a href="https://www.instagram.com/robogals/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/company-beta/873367/"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
                    <a href="https://github.com/robogals/myrobogals"><i class="fa fa-github-square fa-2x" aria-hidden="true"></i></a>
                </div>
                <div class="inner">
                    <p>
                        <a href="/credits/">Credits</a> | <a href="http://robogals.org">robogals.org</a>
                        <br>
                        <i class="fa fa-copyright" aria-hidden="true"></i> Robogals 2010-2017
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{{ MEDIA_URL }}js/jquery.js"></script>
<script src="{{ MEDIA_URL }}resources/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/password_reset_done_v2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>myRobogals</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ MEDIA_URL }}resources/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}resources/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}templates/system/css/landing.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>

<body style="background: url('{{ MEDIA_URL }}images/low-poly-wallpaper-22.png');">
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <div class="heading">
                    <h1 class="cover-heading">Password reset</h1>
                    <h4 class="cover-quote" id="quote"> We've e-mailed you!</h4>
                    <p>
                        Instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly.
                    </p>
                </div>

                <a href="/">
                    <input type="submit" name="Submit" class="btn btn-md btn-default" value="Home"/>
                </a>


                <div class="row">
                    <div class="col-md-4" style=""><a href="/login">Login</a></div>
                    <div class="col-md-1">-</div>
                    <div class="col-md-2"><a href="/join/">Sign up!</a></div>
                    <div class="col-md-1">-</div>
                    <div class="col-md-4"><a href="/support/">Contact Us &amp; FAQ</a></div>
                </div>
            </div>

            <!--Footer -->
            <div class="mastfoot">
                <div class="media-icons">
                    <a href="https://www.facebook.com/robogals/"><i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a>
                    <a href="https://twitter.com/robogals"><i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i></a>
                    <a href="https://www.instagram.com/robogals/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/company-beta/873367/"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
                    <a href="https://github.com/robogals/myrobogals"><i class="fa fa-github-square fa-2x" aria-hidden="true"></i></a>
                </div>
                <div class="inner">
                    <p>
                        <a href="/credits/">Credits</a> | <a href="http://robogals.org">robogals.org</a>
                        <br>
                        <i class="fa fa-copyright" aria-hidden="true"></i> Robogals 2010-2017
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{{ MEDIA_URL }}js/jquery.js"></script>
<script src="{{ MEDIA_URL }}resources/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>