myrobogals/core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, routers
from api_1_0 import views

############# Django REST Framework ###############
api_router = routers.DefaultRouter()
api_router.register(r'users', views.UserViewSet)
api_router.register(r'groups', views.GroupViewSet)
####################################################

# Auto generate/collate Django admin panels
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myrobogals.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # Django REST Framework
    url(r'^api/1.0/', include(api_router.urls)),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
)

myrobogals/rgteaching/urls.py
from django.conf.urls import url

from views import quickentry, eventvisit, school, import_workshop

urlpatterns = [
    # urls for eventvisit.py functions
    url(r'^$', eventvisit.teachhome, name='home'),
    url(r'^list/$', eventvisit.listvisits, name='listvisits'),
    url(r'^printlist/$', eventvisit.printlistvisits),
    url(r'^statshelp/$', eventvisit.statshelp),
    url(r'^(?P<visit_id>\d+)/$', eventvisit.viewvisit, name='viewvisit'),
    url(r'^(?P<visit_id>\d+)/deletemessage/(?P<message_id>\d+)/$', eventvisit.deletemessage),
    url(r'^(?P<visit_id>\d+)/invite/$', eventvisit.invitetovisit),
    url(r'^(?P<visit_id>\d+)/email/$', eventvisit.emailvisitattendees),
    url(r'^(?P<visit_id>\d+)/edit/$', eventvisit.editvisit),
    url(r'^(?P<visit_id>\d+)/stats/$', eventvisit.stats),
    url(r'^(?P<visit_id>\d+)/statsHoursPerPerson/$', eventvisit.statsHoursPerPerson),
    url(r'^(?P<visit_id>\d+)/cancel/$', eventvisit.cancelvisit),
    url(r'^(?P<visit_id>\d+)/reopen/$', eventvisit.reopenvisit),
    url(r'^(?P<event_id>\d+)/rsvp/(?P<user_id>\d+)/(?P<rsvp_type>.+)/$', eventvisit.rsvp),
    url(r'^(?P<school_id>\d+)/newvisit/$', eventvisit.newvisitwithschool),
    url(r'^new/$', eventvisit.newvisit),

    # urls for school.py functions
    url(r'^schools/$', school.listschools),
    url(r'^unstarschool/$', school.unstarschool),
    url(r'^starschool/$', school.starschool),
    url(r'^copyschooldir/$', school.copyschool),
    url(r'^filllatlngschdir/$', school.filllatlngschdir),
    url(r'^schoolsdirectory/(?P<chapterurl>.+)/$', school.schoolsdirectory),
    url(r'^schools/(?P<school_id>\d+)/$', school.editschool),
    url(r'^schools/(?P<school_id>\d+)/delete/$', school.deleteschool),
    url(r'^schools/new/$', school.newschool),

    # url for workshop quick entry
    url(r'^quickentry/$', quickentry.instantvisit, name='quickentry'),

    # url for importing workshops
    url(r'^import/$', import_workshop.ImportWorkshopView.as_view(), name='import_workshops'),
    url(r'^import/download/$', import_workshop.download, name='download')
]

myrobogals/urls.py
from django.conf.urls import url, include, i18n
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve as static_serve_view
from tinymce import urls as tinymce_urls

from myrobogals import settings
from myrobogals.rgchapter import views as rgchapter_views
from myrobogals.rgconf import views as rgconf_views
from myrobogals.rgmain import views as rgmain_views
from myrobogals.rgmessages import views as rgmessages_views
from myrobogals.rgprofile.views import profile_chapter, profile_user, profile_login
from myrobogals.rgweb import views as rgweb_views

urlpatterns = [
	# Home
	url(r'^$', rgmain_views.home),

	# User functions
	url(r'^login/$', profile_login.show_login),
	url(r'^logout/$', auth_views.logout, {'next_page': '/'}),
	url(r'^chpass/$', auth_views.password_change, {'template_name': 'password_change_form.html', 'post_change_redirect': '/profile'}),
	url(r'^forgotpass/done/$', auth_views.password_reset_done, {'template_name': 'password_reset_done.html'}, name='password_reset_done'),
	url(r'^forgotpass/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'password_reset_confirm.html'}),
	url(r'^forgotpass/complete/$', auth_views.password_reset_complete, {'template_name': 'password_reset_complete.html'}, name='password_reset_complete'),
	url(r'^forgotpass/$', auth_views.password_reset, {'template_name': 'password_reset_form.html', 'email_template_name': 'password_reset_email.html'}),
	#url(r'^unsubscribe/(?P<uidb36>.+)/(?P<token>.+)/(?P<step>\d)/$', auth_views.unsubscribe),
	url(r'^join/$', rgchapter_views.joinlist),
	url(r'^join/(?P<chapterurl>.+)/$', profile_user.joinchapter),
	url(r'^welcome/(?P<chapterurl>.+)/$', rgmain_views.welcome),
	url(r'^code/$', profile_login.codeofconduct),
	url(r'^code/help/$', profile_user.conduct_help),

	# Profile menu
	url(r'^profile/$', profile_user.redirtoself),
	url(r'^profile/contactdirectory/$', profile_chapter.contactdirectory),
	url(r'^profile/edit/$', profile_user.redirtoeditself),
	url(r'^profile/mobverify/$', profile_user.mobverify),
	#url(r'^profile/(?P<username>.+)/edit/profileimage/$', 'profileimages.views.upload_profile_image'),
	url(r'^profile/(?P<username>.+)/edit/$', profile_user.edituser),
	url(r'^profile/(?P<username>.+)/genpw/$', profile_user.genpw),
	url(r'^profile/(?P<username>.+)/$', profile_user.detail),
	
	# Chapters menu
	url(r'^chapters/$', rgchapter_views.list),
	url(r'^chapters/awards/$', rgchapter_views.awards),
	url(r'^chapters/awards/(?P<award_id>\d+)/$', rgchapter_views.awardsdesc),
	url(r'^chapters/my/$', rgchapter_views.redirtomy),
	url(r'^chapters/localtimes/$', rgchapter_views.localtimes),
	url(r'^chapters/(?P<chapterurl>.+)/lists/(?P<list_id>\d+)/edit/$', profile_chapter.edituserlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/(?P<list_id>\d+)/$', profile_chapter.viewlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/add/$', profile_chapter.adduserlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/$', profile_chapter.listuserlists),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/help/unis/$', profile_chapter.unilist),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/help/$', profile_chapter.importusershelp),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/$', profile_chapter.importusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/export/$', profile_chapter.exportusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/add/$', profile_chapter.adduser),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/$', profile_chapter.editusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/execs/remove/(?P<username>.+)/$', profile_chapter.remove_exec),
	url(r'^chapters/(?P<chapterurl>.+)/edit/execs/$', profile_chapter.editexecs),
	url(r'^chapters/(?P<chapterurl>.+)/edit/status/$', profile_chapter.editstatus),
	url(r'^chapters/(?P<chapterurl>.+)/edit/$', rgchapter_views.editchapter),
	url(r'^chapters/(?P<chapterurl>.+)/websitedetails/$', rgweb_views.websitedetails),
	url(r'^chapters/(?P<chapterurl>.+)/join/$', profile_user.joinchapter),
	url(r'^chapters/(?P<chapterurl>.+)/$', rgchapter_views.detail),

	# Conferences submenu
	url(r'^conferences/$', rgconf_views.home),
	url(r'^conferences/(?P<conf_id>\d+)/$', rgconf_views.rsvplist),
	url(r'^conferences/(?P<conf_id>\d+)/nametags\.csv$', rgconf_views.nametagscsv),
	url(r'^conferences/(?P<conf_id>\d+)/email/$', rgconf_views.rsvpemail),
	url(r'^conferences/(?P<conf_id>\d+)/(?P<username>.+)/rsvp/$', rgconf_views.editrsvp),
	url(r'^conferences/(?P<conf_id>\d+)/(?P<username>.+)/invoice/$', rgconf_views.showinvoice),

	# Forums
	# url(r'^forums/', include('myrobogals.rgforums.urls')),

	# Workshops menu
	url(r'^teaching/', include('myrobogals.rgteaching.urls', namespace='teaching')),

	# Reporting metrics
	url(r'^reports/', include('myrobogals.rgreport.urls', namespace='reports')),

	# Email & SMS menu
	url(r'^messages/img/(?P<msgid>\d+)/(?P<filename>.+)$', rgmessages_views.serveimg),
	url(r'^messages/(?P<msgid>\d+)/(?P<issue>.+)/$', rgmessages_views.servenewsletter),
	url(r'^messages/sms/write/$', rgmessages_views.writesms),
	url(r'^messages/sms/done/$', rgmessages_views.smsdone),
	url(r'^messages/sms/overlimit/$', rgmessages_views.smsoverlimit),
	url(r'^messages/email/write/$', rgmessages_views.writeemail),
	url(r'^messages/setmaxuploadfilesize/$', rgmessages_views.setmaxuploadfilesize),
	url(r'^messages/email/done/$', rgmessages_views.emaildone),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/$', rgmessages_views.newslettercp),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/import/$', rgmessages_views.importsubscribers),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/import/help/$', rgmessages_views.importsubscribershelp),
	url(r'^messages/emailrecipients/(?P<email_id>\d+)/$', rgmessages_views.emailrecipients),
	url(r'^messages/smsrecipients/(?P<sms_id>\d+)/$', rgmessages_views.smsrecipients),
	url(r'^messages/showemail/(?P<email_id>\d+)/$', rgmessages_views.showemail),
	url(r'^messages/downloademailfile/(?P<email_id>\d+)/(?P<file_name>.+)/$', rgmessages_views.downloademailfile),
	url(r'^messages/history/$', rgmessages_views.msghistory),
	url(r'^messages/previewemail/$', rgmessages_views.previewemail),
	
	# Changelogs
	url(r'^changelogs/$', rgmain_views.changelogs),

	# Wiki
	url(r'^wiki/$', rgmain_views.wiki),

	# Static pages
	url(r'^credits/$', rgmain_views.credits),
	url(r'^support/$', rgmain_views.support),

	# Careers newsletter API
	url(r'^api/newslettercareers/$', rgmessages_views.careersapi),
	# Amplifier newsletter API
	url(r'^api/newsletter/$', rgmessages_views.api),
	# SMSGlobal delivery receipts API
	url(r'^api/dlr/$', rgmessages_views.dlrapi),
	# Google Maps KML API
	url(r'^api/chapter-map.kml', rgchapter_views.chaptermap),
	# Delete user API
	url(r'^delete/user/(?P<userpk>\d+)/$', profile_chapter.deleteuser),

	# i18n helpers
	url(r'^i18n/', include(i18n)),
	# TinyMCE helpers
	url(r'^tinymce/', include(tinymce_urls)),
	
	# Admin site
	url(r'^topsecretarea/', include(admin.site.urls)),
]

# If running the local development server - this will serve the media files through it too
if settings.DEBUG:
	urlpatterns.append(url(r'^rgmedia/(?P<path>.*)$', static_serve_view, {'document_root': settings.MEDIA_ROOT}))

# Custom view for 500 Internal Server Error
handler500 = 'myrobogals.rgmain.views.servererror'

myrobogals/rgteaching/views/tools.py
from django.core.paginator import Paginator, EmptyPage

"""
Helpful functions for rgteaching views
"""


# Creates paginator for tables greater than size 'sizeOfList'
def paginatorRender(request, list_of_objects, size_of_list):
    paginator = Paginator(list_of_objects, size_of_list)
    page = request.GET.get('page')
    try:
        visits = paginator.page(page)
    except EmptyPage:
        visits = paginator.page(paginator.num_pages)
    except:
        visits = paginator.page(1)

    return visits

myrobogals/rgteaching/templates/includes/attendees.html
{% load static %}
{% load widget_tweaks %}

<ul class="nav nav-tabs" id="pills-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="pills-attending-tab" data-toggle="pill" href="#pills-attending" role="tab" aria-controls="pills-attending" aria-expanded="true">ATTENDING</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-interested-tab" data-toggle="pill" href="#pills-interested" role="tab" aria-controls="pills-interested" aria-expanded="true">INTERESTED</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-notgoing-tab" data-toggle="pill" href="#pills-notgoing" role="tab" aria-controls="pills-notgoing" aria-expanded="true">NOT GOING</a>
  </li>

</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-attending" role="tabpanel" aria-labelledby="pills-attending-tab">

    <div class="row" style="margin-top: 14px;">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>
    <hr/>

    <div class="row">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>

    <hr/>
    <div class="row">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>
  </div>

  <div class="tab-pane fade" id="pills-interested" role="tabpanel" aria-labelledby="pills-interested-tab">
    <div class="row" style="margin-top: 14px;">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>
    <hr/>

    <div class="row">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>

    <hr/>
    <div class="row">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>
    <hr/>
    <div class="row">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>
    <hr/>

    <div class="row">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>

    <hr/>
    <div class="row">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-notgoing" role="tabpanel" aria-labelledby="pills-notgoing-tab">
    <div class="row" style="margin-top: 14px;">
      <div class="col-2" style="display: flex; align-items: center; justify-content: center">
        <img style="border-radius: 360px; height: 3rem;" src="{% static "myrobogals/img/profile_picture.png" %}"/>
      </div>
      <div class="col-9">
        Mark Jacobs
        <br/>
        <i class="fa fa-check-circle text-success" aria-hidden="true"></i> Trained <i class="fa fa-times-circle text-danger" aria-hidden="true"></i> Checked
      </div>
    </div>
  </div>
</div>

myrobogals/rgteaching/templates/includes/edit_event.html
{% load widget_tweaks %}

<form action="{% url 'teaching:viewvisit' id %}" method="post"> {% csrf_token %}
  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Event</label>
    <div class="col-10">
      <!-- Smartypants...-->
      {{ event_form.event|add_class:"form-control"|attr:"disabled"}}
    </div>
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Location</label>
    <div class="col-10">
      {% if not event_form.location.errors %}
        {{ event_form.location|add_class:"form-control"|attr:"The location where the event is being held" }}
      {% else %}
        {{ event_form.location|add_class:"form-control is-invalid"|attr:"The location where the event is being held" }}
        <div class="invalid-feedback">
          {% for error in event_form.location.errors %}
            {{ error }}
          {% endfor %}
        </div>
        </div>
      {% endif %}
    </div>
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Date</label>
    {% if not event_form.date.errors %}
      <div class="input-group date col-5" data-provide="datepicker">
        {{ event_form.date|add_class:"form-control" }}
        <div class="input-group-addon">
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </div>
      </div>
    {% else %}
      <div class="input-group date col-5" data-provide="datepicker">
        {{ event_form.date|add_class:"form-control is-invalid" }}
        <div class="input-group-addon">
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </div>
      </div>
      <div class="invalid-feedback" style="display: block;">
        {% for error in event_form.date.errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Time</label>
    <div class="input-group bootstrap-timepicker timepicker col-5">
      {% if not event_form.start_time.errors %}
        {{ event_form.start_time|add_class:"form-control input-small"|attr:"id:timepicker1" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
      {% else %}
        {{ event_form.start_time|add_class:"form-control input-small is-invalid"|attr:"id:timepicker1" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        <div class="invalid-feedback">
          {% for error in event_form.start_time.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <div class="input-group bootstrap-timepicker timepicker col-5">
      {% if not event_form.end_time.errors %}
        {{ event_form.end_time|add_class:"form-control input-small"|attr:"id:timepicker2" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
      {% else %}
        {{ event_form.end_time|add_class:"form-control input-small is-invalid"|attr:"id:timepicker2" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        <div class="invalid-feedback">
          {% for error in event_form.end_time.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>

  <div class="form-group row">
    <label for="message-text" class="form-control-label col-2">Year Level:</label>
    <div class="col-10">
      {{ event_form.yearlvl|add_class:"form-control" }}
    </div>
  </div>

  <div class="form-group row">
    <label for="message-text" class="form-control-label col-2">Details:</label>
    <div class="col-10">
      {{ event_form.notes|add_class:"form-control" }}
    </div>
  </div>

  <button type="submit" class="btn btn-primary">Save</button>

</form>

myrobogals/rgteaching/templates/includes/new_event.html
{% load widget_tweaks %}

<form action="{% url 'teaching:home' %}" method="post"> {% csrf_token %}
  <div class="form-group">
    <div class="row">
      <div class="col-9"></div>
      <div class="col-3">{{ event_form.privacy|add_class:"form-control" }}</div>
    </div>
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Event</label>
    <div class="col-10">
      {% if not event_form.event.errors %}
        {{ event_form.event|add_class:"form-control typeahead"|attr:"placeholder:Enter the school or event's name"|attr:"autocomplete:off" }}
      {% else %}
        {{ event_form.event|add_class:"form-control is-invalid"|attr:"placeholder:Enter the school or event's name data-provide:typeahead" }}
        <div class="invalid-feedback">
          {% for error in event_form.event.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Location</label>
    <div class="col-10">
      {% if not event_form.location.errors %}
        {{ event_form.location|add_class:"form-control"|attr:"The location where the event is being held" }}
      {% else %}
        {{ event_form.location|add_class:"form-control is-invalid"|attr:"The location where the event is being held" }}
        <div class="invalid-feedback">
          {% for error in event_form.location.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Date</label>
    {% if not event_form.date.errors %}
      <div class="input-group date col-5" data-provide="datepicker">
        {{ event_form.date|add_class:"form-control" }}
        <div class="input-group-addon">
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </div>
      </div>
    {% else %}
      <div class="input-group date col-5" data-provide="datepicker">
        {{ event_form.date|add_class:"form-control is-invalid" }}
        <div class="input-group-addon">
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </div>
      </div>
      <div class="invalid-feedback" style="display: block;">
        {% for error in event_form.date.errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Time</label>
    <div class="input-group bootstrap-timepicker timepicker col-5">
      {% if not event_form.start_time.errors %}
        {{ event_form.start_time|add_class:"form-control input-small"|attr:"id:timepicker1" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
      {% else %}
        {{ event_form.start_time|add_class:"form-control input-small is-invalid"|attr:"id:timepicker1" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        <div class="invalid-feedback">
          {% for error in event_form.start_time.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <div class="input-group bootstrap-timepicker timepicker col-5">
      {% if not event_form.end_time.errors %}
        {{ event_form.end_time|add_class:"form-control input-small"|attr:"id:timepicker2" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
      {% else %}
        {{ event_form.end_time|add_class:"form-control input-small is-invalid"|attr:"id:timepicker2" }}
        <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        <div class="invalid-feedback">
          {% for error in event_form.end_time.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>

  <div class="form-group row">
    <label for="message-text" class="form-control-label col-2">Year Level:</label>
    <div class="col-10">
      {{ event_form.yearlvl|add_class:"form-control" }}
    </div>
  </div>

  <div class="form-check">
    <label class="form-check-label">
      <input type="checkbox" class="form-check-input"/>
      Recurring Event
    </label>
  </div>

  <div class="form-group row">
    <label for="message-text" class="form-control-label col-2">Details:</label>
    <div class="col-10">
      {{ event_form.notes|add_class:"form-control" }}
    </div>
  </div>

  <button type="submit" class="btn btn-primary">Create event</button>

</form>