myrobogals/core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, routers
from api_1_0 import views

############# Django REST Framework ###############
api_router = routers.DefaultRouter()
api_router.register(r'users', views.UserViewSet)
api_router.register(r'groups', views.GroupViewSet)
####################################################

# Auto generate/collate Django admin panels
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myrobogals.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # Django REST Framework
    url(r'^api/1.0/', include(api_router.urls)),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
)

myrobogals/rgteaching/urls.py
from django.conf.urls import url

from views import quickentry, eventvisit, school, import_workshop

urlpatterns = [
    # urls for eventvisit.py functions
    url(r'^$', eventvisit.teachhome, name='home'),
    url(r'^list/$', eventvisit.listvisits, name='listvisits'),
    url(r'^printlist/$', eventvisit.printlistvisits),
    url(r'^statshelp/$', eventvisit.statshelp),
    url(r'^(?P<visit_id>\d+)/$', eventvisit.viewvisit, name='viewvisit'),
    url(r'^(?P<visit_id>\d+)/deletemessage/(?P<message_id>\d+)/$', eventvisit.deletemessage),
    url(r'^(?P<visit_id>\d+)/invite/$', eventvisit.invitetovisit),
    url(r'^(?P<visit_id>\d+)/email/$', eventvisit.emailvisitattendees),
    url(r'^(?P<visit_id>\d+)/edit/$', eventvisit.editvisit),
    url(r'^(?P<visit_id>\d+)/stats/$', eventvisit.stats),
    url(r'^(?P<visit_id>\d+)/statsHoursPerPerson/$', eventvisit.statsHoursPerPerson),
    url(r'^(?P<visit_id>\d+)/cancel/$', eventvisit.cancelvisit),
    url(r'^(?P<visit_id>\d+)/reopen/$', eventvisit.reopenvisit),
    url(r'^(?P<event_id>\d+)/rsvp/(?P<user_id>\d+)/(?P<rsvp_type>.+)/$', eventvisit.rsvp),
    url(r'^(?P<school_id>\d+)/newvisit/$', eventvisit.newvisitwithschool),
    url(r'^new/$', eventvisit.newvisit),

    # urls for school.py functions
    url(r'^schools/$', school.listschools),
    url(r'^unstarschool/$', school.unstarschool),
    url(r'^starschool/$', school.starschool),
    url(r'^copyschooldir/$', school.copyschool),
    url(r'^filllatlngschdir/$', school.filllatlngschdir),
    url(r'^schoolsdirectory/(?P<chapterurl>.+)/$', school.schoolsdirectory),
    url(r'^schools/(?P<school_id>\d+)/$', school.editschool),
    url(r'^schools/(?P<school_id>\d+)/delete/$', school.deleteschool),
    url(r'^schools/new/$', school.newschool),

    # url for workshop quick entry
    url(r'^quickentry/$', quickentry.instantvisit, name='quickentry'),

    # url for importing workshops
    url(r'^import/$', import_workshop.ImportWorkshopView.as_view(), name='import_workshops'),
    url(r'^import/download/$', import_workshop.download, name='download')
]

myrobogals/urls.py
from django.conf.urls import url, include, i18n
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve as static_serve_view
from tinymce import urls as tinymce_urls

from myrobogals import settings
from myrobogals.rgchapter import views as rgchapter_views
from myrobogals.rgconf import views as rgconf_views
from myrobogals.rgmain import views as rgmain_views
from myrobogals.rgmessages import views as rgmessages_views
from myrobogals.rgprofile.views import profile_chapter, profile_user, profile_login
from myrobogals.rgweb import views as rgweb_views

urlpatterns = [
	# Home
	url(r'^$', rgmain_views.home),

	# User functions
	url(r'^login/$', profile_login.show_login),
	url(r'^logout/$', auth_views.logout, {'next_page': '/'}),
	url(r'^chpass/$', auth_views.password_change, {'template_name': 'password_change_form.html', 'post_change_redirect': '/profile'}),
	url(r'^forgotpass/done/$', auth_views.password_reset_done, {'template_name': 'password_reset_done.html'}, name='password_reset_done'),
	url(r'^forgotpass/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'password_reset_confirm.html'}),
	url(r'^forgotpass/complete/$', auth_views.password_reset_complete, {'template_name': 'password_reset_complete.html'}, name='password_reset_complete'),
	url(r'^forgotpass/$', auth_views.password_reset, {'template_name': 'password_reset_form.html', 'email_template_name': 'password_reset_email.html'}),
	#url(r'^unsubscribe/(?P<uidb36>.+)/(?P<token>.+)/(?P<step>\d)/$', auth_views.unsubscribe),
	url(r'^join/$', rgchapter_views.joinlist),
	url(r'^join/(?P<chapterurl>.+)/$', profile_user.joinchapter),
	url(r'^welcome/(?P<chapterurl>.+)/$', rgmain_views.welcome),
	url(r'^code/$', profile_login.codeofconduct),
	url(r'^code/help/$', profile_user.conduct_help),

	# Profile menu
	url(r'^profile/$', profile_user.redirtoself),
	url(r'^profile/contactdirectory/$', profile_chapter.contactdirectory),
	url(r'^profile/edit/$', profile_user.redirtoeditself),
	url(r'^profile/mobverify/$', profile_user.mobverify),
	#url(r'^profile/(?P<username>.+)/edit/profileimage/$', 'profileimages.views.upload_profile_image'),
	url(r'^profile/(?P<username>.+)/edit/$', profile_user.edituser),
	url(r'^profile/(?P<username>.+)/genpw/$', profile_user.genpw),
	url(r'^profile/(?P<username>.+)/$', profile_user.detail),
	
	# Chapters menu
	url(r'^chapters/$', rgchapter_views.list),
	url(r'^chapters/awards/$', rgchapter_views.awards),
	url(r'^chapters/awards/(?P<award_id>\d+)/$', rgchapter_views.awardsdesc),
	url(r'^chapters/my/$', rgchapter_views.redirtomy),
	url(r'^chapters/localtimes/$', rgchapter_views.localtimes),
	url(r'^chapters/(?P<chapterurl>.+)/lists/(?P<list_id>\d+)/edit/$', profile_chapter.edituserlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/(?P<list_id>\d+)/$', profile_chapter.viewlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/add/$', profile_chapter.adduserlist),
	url(r'^chapters/(?P<chapterurl>.+)/lists/$', profile_chapter.listuserlists),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/help/unis/$', profile_chapter.unilist),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/help/$', profile_chapter.importusershelp),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/import/$', profile_chapter.importusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/export/$', profile_chapter.exportusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/add/$', profile_chapter.adduser),
	url(r'^chapters/(?P<chapterurl>.+)/edit/users/$', profile_chapter.editusers),
	url(r'^chapters/(?P<chapterurl>.+)/edit/execs/remove/(?P<username>.+)/$', profile_chapter.remove_exec),
	url(r'^chapters/(?P<chapterurl>.+)/edit/execs/$', profile_chapter.editexecs),
	url(r'^chapters/(?P<chapterurl>.+)/edit/status/$', profile_chapter.editstatus),
	url(r'^chapters/(?P<chapterurl>.+)/edit/$', rgchapter_views.editchapter),
	url(r'^chapters/(?P<chapterurl>.+)/websitedetails/$', rgweb_views.websitedetails),
	url(r'^chapters/(?P<chapterurl>.+)/join/$', profile_user.joinchapter),
	url(r'^chapters/(?P<chapterurl>.+)/$', rgchapter_views.detail),

	# Conferences submenu
	url(r'^conferences/$', rgconf_views.home),
	url(r'^conferences/(?P<conf_id>\d+)/$', rgconf_views.rsvplist),
	url(r'^conferences/(?P<conf_id>\d+)/nametags\.csv$', rgconf_views.nametagscsv),
	url(r'^conferences/(?P<conf_id>\d+)/email/$', rgconf_views.rsvpemail),
	url(r'^conferences/(?P<conf_id>\d+)/(?P<username>.+)/rsvp/$', rgconf_views.editrsvp),
	url(r'^conferences/(?P<conf_id>\d+)/(?P<username>.+)/invoice/$', rgconf_views.showinvoice),

	# Forums
	# url(r'^forums/', include('myrobogals.rgforums.urls')),

	# Workshops menu
	url(r'^teaching/', include('myrobogals.rgteaching.urls', namespace='teaching')),

	# Reporting metrics
	url(r'^reports/', include('myrobogals.rgreport.urls', namespace='reports')),

	# Email & SMS menu
	url(r'^messages/img/(?P<msgid>\d+)/(?P<filename>.+)$', rgmessages_views.serveimg),
	url(r'^messages/(?P<msgid>\d+)/(?P<issue>.+)/$', rgmessages_views.servenewsletter),
	url(r'^messages/sms/write/$', rgmessages_views.writesms),
	url(r'^messages/sms/done/$', rgmessages_views.smsdone),
	url(r'^messages/sms/overlimit/$', rgmessages_views.smsoverlimit),
	url(r'^messages/email/write/$', rgmessages_views.writeemail),
	url(r'^messages/setmaxuploadfilesize/$', rgmessages_views.setmaxuploadfilesize),
	url(r'^messages/email/done/$', rgmessages_views.emaildone),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/$', rgmessages_views.newslettercp),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/import/$', rgmessages_views.importsubscribers),
	url(r'^messages/newsletters/(?P<newsletter_id>\d+)/import/help/$', rgmessages_views.importsubscribershelp),
	url(r'^messages/emailrecipients/(?P<email_id>\d+)/$', rgmessages_views.emailrecipients),
	url(r'^messages/smsrecipients/(?P<sms_id>\d+)/$', rgmessages_views.smsrecipients),
	url(r'^messages/showemail/(?P<email_id>\d+)/$', rgmessages_views.showemail),
	url(r'^messages/downloademailfile/(?P<email_id>\d+)/(?P<file_name>.+)/$', rgmessages_views.downloademailfile),
	url(r'^messages/history/$', rgmessages_views.msghistory),
	url(r'^messages/previewemail/$', rgmessages_views.previewemail),
	
	# Changelogs
	url(r'^changelogs/$', rgmain_views.changelogs),

	# Wiki
	url(r'^wiki/$', rgmain_views.wiki),

	# Static pages
	url(r'^credits/$', rgmain_views.credits),
	url(r'^support/$', rgmain_views.support),

	# Careers newsletter API
	url(r'^api/newslettercareers/$', rgmessages_views.careersapi),
	# Amplifier newsletter API
	url(r'^api/newsletter/$', rgmessages_views.api),
	# SMSGlobal delivery receipts API
	url(r'^api/dlr/$', rgmessages_views.dlrapi),
	# Google Maps KML API
	url(r'^api/chapter-map.kml', rgchapter_views.chaptermap),
	# Delete user API
	url(r'^delete/user/(?P<userpk>\d+)/$', profile_chapter.deleteuser),

	# i18n helpers
	url(r'^i18n/', include(i18n)),
	# TinyMCE helpers
	url(r'^tinymce/', include(tinymce_urls)),
	
	# Admin site
	url(r'^topsecretarea/', include(admin.site.urls)),
]

# If running the local development server - this will serve the media files through it too
if settings.DEBUG:
	urlpatterns.append(url(r'^rgmedia/(?P<path>.*)$', static_serve_view, {'document_root': settings.MEDIA_ROOT}))

# Custom view for 500 Internal Server Error
handler500 = 'myrobogals.rgmain.views.servererror'

myrobogals/rgteaching/views/tools.py
from django.core.paginator import Paginator, EmptyPage

"""
Helpful functions for rgteaching views
"""


# Creates paginator for tables greater than size 'sizeOfList'
def paginatorRender(request, list_of_objects, size_of_list):
    paginator = Paginator(list_of_objects, size_of_list)
    page = request.GET.get('page')
    try:
        visits = paginator.page(page)
    except EmptyPage:
        visits = paginator.page(paginator.num_pages)
    except:
        visits = paginator.page(1)

    return visits

myrobogals/rgteaching/templates/new_visit-v2.html
{% extends "base-v2.html" %}

{% block title %} New Event {% endblock %}
{% block pagetitle %} Create New Event{% endblock %}

{% block content %}
  <div class="tile">
    <h2 class="rg-page-header">
      New Event
    </h2>
    {% include "includes/new_event.html" %}
  </div>
{% endblock %}

{% block script %}
  <script>
      $('.datepicker').datepicker();
      $('#timepicker1').timepicker({
          icons: {
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down'
          }
      });
      $('#timepicker2').timepicker({
          icons: {
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down'
          }
      });
  </script>
{% endblock %}

myrobogals/rgteaching/templates/quick_entry-v2.html
{% extends "base-v2.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Enter Stats" %}{% endblock %}

{% block pagetitle %}{% trans "Enter Stats" %}{% endblock %}

{% block content %}


  <div class="tile">
    <h2 class="rg-page-header">
      Basic Information
    </h2>

    <form>

      <div class="form-group row" style="justify-content: flex-end; margin-right: 0;">
        {{ form2.visit_type|add_class:"custom-select"|attr:"style:font-weight:bold;" }}
      </div>

      <div class="form-group row">
        <label for="recipient-name" class="form-control-label col-2">Event</label>
        <div class="col-10">
          <input placeholder="Enter the school or event's name" type="text" class="form-control" id="recipient-name">
        </div>
      </div>
      <div class="form-group row">
        <label for="recipient-name" class="form-control-label col-2">Location</label>
        <div class="col-10">
          <input placeholder="The location where the event is being held" type="text" class="form-control" id="recipient-name">
        </div>
      </div>
      <div class="form-group row">
        <label for="recipient-name" class="form-control-label col-2">Date</label>
        <div class="input-group date col-5" data-provide="datepicker">
          <input type="text" class="form-control" value="12-02-2012">
          <div class="input-group-addon">
            <i class="fa fa-calendar" aria-hidden="true"></i>
          </div>
        </div>
        <div class="col-5">
        </div>
      </div>

      <div class="form-group row">
        <label for="recipient-name" class="form-control-label col-2">Time</label>
        <div class="input-group bootstrap-timepicker timepicker col-5">
          <input id="timepicker1" type="text" class="form-control input-small">
          <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        </div>
        <div class="input-group bootstrap-timepicker timepicker col-5">
          <input id="timepicker2" type="text" class="form-control input-small">
          <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        </div>
      </div>

      <div class="form-group row">
        <label for="message-text" class="form-control-label col-2">Description:</label>
        <div class="col-10">
          {{ form2.notes|add_class:"form-control"|attr:"id:message-text" }}
        </div>
      </div>

      <div class="row">
        <label class="col-2">Selected Attended:</label>
        <div class="form-group col-5">
          <select multiple class="form-control" id="exampleSelect2">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>
        </div>

        <div class="form-group col-5">
          <select multiple class="form-control" id="exampleSelect2">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-2">Enter Stats:</label>
        <div class="col-10">
          <table class="table table-hover">
            <thead class="rg-thead-inverse">
            <tr>
              <th></th>
              <th colspan="2">Girls</th>
              <th colspan="2">Boys</th>
            </tr>
            </thead>
            <thead>
            <tr>
              <th></th>
              <th>First</th>
              <th>Repeat</th>
              <th>First</th>
              <th>Repeat</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <th scope="row">Primary School</th>
              <td>{{ form2.primary_girls_first }}</td>
              <td>{{ form2.primary_girls_repeat }}</td>
              <td>{{ form2.primary_boys_first }}</td>
              <td>{{ form2.primary_boys_repeat }}</td>
            </tr>
            <tr>
              <th scope="row">High School</th>
              <td>{{ form2.high_girls_first }}</td>
              <td>{{ form2.high_girls_repeat }}</td>
              <td>{{ form2.high_boys_first }}</td>
              <td>{{ form2.high_boys_repeat }}</td>
            </tr>
            <tr>
              <th scope="row">Other</th>
              <td>{{ form2.other_girls_first }}</td>
              <td>{{ form2.other_girls_repeat }}</td>
              <td>{{ form2.other_boys_first }}</td>
              <td>{{ form2.other_boys_repeat }}</td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>


      <button type="button" class="btn btn-primary">Save Stats</button>
    </form>
  </div>

{% endblock %}

{% block script %}
  <script>
      $('.datepicker').datepicker();
      $('#timepicker1').timepicker({
          icons: {
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down'
          }
      });
      $('#timepicker2').timepicker({
          icons: {
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down'
          }
      });
  </script>
{% endblock %}

myrobogals/rgteaching/templates/teaching_home-v2.html
{% extends "base-v2.html" %}
{% load i18n %}
{% load tz %}
{% load widget_tweaks %}

{% block title %}{% trans "Events Summary" %}{% endblock %}

{% block pagetitle %}{% trans "Events Summary" %}{% endblock %}

{% block content %}


  <div class="tile">
    <h2 class="rg-page-header">
      Your Chapter's Progress
    </h2>

    <div class="text-muted">
      Chapter's Target: {{ chapter.goal }}
    </div>

    <div class="progress">
      <div class="progress-bar bg-success-secondary" role="progressbar" style="{{ chapter.sum_percent }}" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

    <div class="text-muted">
      Started: {{ chapter.goal_start }}
    </div>

  </div>

  <div class="tile">
    <h2 class="rg-page-header">
      Upcoming Events
      <button type="button" style="float:right; margin-top:-3px;" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModal">
        {% trans "NEW EVENT" %}
      </button>
    </h2>

    <table class="table table-striped">
      <thead class="rg-thead-inverse">
      <tr>
        <th>Event</th>
        <th>Date</th>
        <th>Time</th>
        <th style="text-align: center;">Attending</th>
        <th style="text-align: center;">Privacy</th>
      </tr>
      </thead>

      <tbody>
      {% for e in upcoming_events %}
        <tr>
          <th scope="row"><a href="{% url 'teaching:viewvisit' e.id %}">{{ e.school }}</a></th>
          <td>{{ e.visit_start|date:_("DATE_FORMAT") }}</td>
          <td>{{ e.visit_start|date:_("TIME_FORMAT") }} to {{ e.visit_end|date:_("TIME_FORMAT") }}</td>
          <td style="text-align: center;">10</td>
          <td style="text-align: center;">Private</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

  </div>

  <div class="tile">
    <h2 class="rg-page-header">
      Recent Events
      <a href="{% url "teaching:import_workshops" %}" style="float:right; margin-top:-3px; margin-left: 5px;" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">
        {% trans "IMPORT WORKSHOPS" %}</a>
      <a href="{% url "teaching:quickentry" %}" style="float:right; margin-top:-3px; margin-left: 5px;" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">{% trans "QUICK ENTRY" %}</a>
    </h2>

    <table class="table table-striped">
      <thead class="rg-thead-inverse">
      <tr>
        <th>Event</th>
        <th>Date</th>
        <th style="text-align: center;">Attended</th>
        <th style="text-align: center;">Stats</th>
        <th style="text-align: center;">Action</th>
      </tr>
      </thead>

      <tbody>
      {% for e in upcoming_events %}
        <tr>
          <th scope="row">{{ e.school }}</th>
          <td>{{ e.visit_end }}</td>
          <td style="text-align: center;">8</td>
          <td style="text-align: center;">22</td>
          <td style="text-align: center;"><a href="#">View</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    <a href="{% url "teaching:listvisits" %}">See all events</a>
  </div>

  <!-- Create new event modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create New Event</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times</span>
          </button>
        </div>
        <div class="modal-body">
          {% include "includes/new_event.html" %}
        </div>
      </div>
    </div>
  </div>
  <!-- Create new event modal -->
{% endblock %}

{% block script %}
  <script>
      $('.datepicker').datepicker();
      $('#timepicker1').timepicker({
          icons: {
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down'
          }
      });
      $('#timepicker2').timepicker({
          icons: {
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down'
          }
      });
  </script>
{% endblock %}

myrobogals/rgteaching/templates/visit_list-v2.html
{% extends "base-v2.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Workshops and events" %}{% endblock %}

{% block pagetitle %}{% trans "Workshops and events" %}{% endblock %}

{% block content %}

  <div class="tile">
    <h2 class="rg-page-header">
      Events List
      {% if user.is_staff %}
        <a href="#" style="float:right; margin-top:-3px;" class="btn btn-primary btn-sm" role="button" aria-pressed="true">{% trans "NEW EVENT" %}</a>
      {% endif %}
    </h2>

      {% if showall %}
        <form action="/teaching/list/" method="GET"> {% csrf_token %}
          {{ chapterform.chapter|add_class:"custom-select" }}
          <button type="submit" class="btn btn-primary btn-sm">Filter Events</button>
        </form>
      {% endif %}
  </p>

    <table class="table table-hover table-sm">
      <thead class="rg-thead-inverse">
      <tr>
        <th>School</th>
        <th>Date</th>
        <th>Status</th>
        {% if showall %}
          <th>Chapter</th>
        {% endif %}
        <th>
          View
        </th>
      </tr>
      </thead>
      {% for v in visits %}

        <tr>
          <th scope="row">{{ v.school }}</th>
          <td>{{ v.visit_start|date:_("DATE_FORMAT") }}</td>
          <td>{{ v.get_status_display }}</td>
          {% if showall %}
            <td>{{ v.chapter }}</td>
          {% endif %}
          <td><a href="/teaching/{{ v.pk }}/">{% trans "View" %}</a></td>
        </tr>
      {% endfor %}
    </table>
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if visits.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ visits.previous_page_number }}">Previous</a></li>
        {% endif %}

        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
        <li class="page-item"><a class="page-link" href="?page=2">2</a></li>
        {#    <li class="page-item"><a class="page-link" href="?page={{visits.last_page_number}}">{{visits.last_page_number}}</a></li>#}
        {#    <li class="page-item"><a class="page-link" href="?page={{visits.next_page_number}}">Next</a></li>#}
      </ul>
    </nav>
  </div>

{% endblock %}